// import type { Metadata } from "next";
import { verifyPublicSession } from "@/actions/verify-public-session";
import ModeToggle from "@/components/ModeToggle";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await verifyPublicSession()

  return (
    <div>
      <main className="w-full">
        {children}
      </main>
      <div className="absolute top-4 right-4">
        <ModeToggle/>
      </div>
    </div>
  );
}
